lint:
  build: .
  environment:
    - TERM=xterm-256color
  working_dir: /api
  volumes:
   - ./src:/api/src
   - ./.eslintignore:/api/.eslintignore
   - ./.eslintrc.js:/api/.eslintrc.js
  command: npm run lint
